language: python
dist: xenial
sudo: required
cache: pip
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
matrix:
  exclude:
    - env: DJANGO=2.0
      python: "2.7"
    - env: DJANGO=2.1
      python: "2.7"
    - env: DJANGO=1.11
      python: "3.7"
addons:
  chrome: stable
  apt:
    packages:
    - enchant
before_install:
  - wget https://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - chmod +x chromedriver
  - export PATH=$TRAVIS_BUILD_DIR:$PATH
install:
  - pip install -q codecov tox tox-travis
script: tox
after_success:
 - codecov
before_deploy:
  - pip install Sphinx
  - cd docs
  - make html
deploy:
  - provider: pages
    local-dir: docs/_build/html
    github-token: $GH_TOKEN
    skip_cleanup: true
    on:
      branch: master
      python: "3.7"
      condition: $DJANGO=2.1
  - provider: pypi
    skip_cleanup: true
    user: $PYPI_USER
    password: $PYPI_PASS
    distributions: "sdist bdist_wheel"
    on:
      tags: true
      python: "3.7"
      condition: $DJANGO=2.1
notifications:
  email: false
