language: python
sudo: required
python:
  - "2.7"
  - "3.6"
env:
  - DJANGO_VERSION=1.8.17
  - DJANGO_VERSION=1.9.12
  - DJANGO_VERSION=1.10.6
  - DJANGO_VERSION=1.11.12
  - DJANGO_VERSION=2.0.4
matrix:
  exclude:
    - env: DJANGO_VERSION=2.0
      python: "2.7"
addons:
  chrome: stable
  apt:
    packages:
    - enchant
before_install:
  - pip install codecov
  - wget https://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - chmod +x chromedriver
  - export PATH=$TRAVIS_BUILD_DIR:$PATH
install:
  - pip install -q -r test_requirements.txt
  - pip install -q Django==$DJANGO_VERSION
script:
#  - python setup.py install
  - coverage run manage.py test test_tinymce
after_success:
 - codecov
before_deploy: wget https://raw.githubusercontent.com/romanvm/travis_scripts/master/publish_docs.py
deploy:
  - provider: script
    script: python publish_docs.py
    skip_cleanup: true
    on:
      branch: master
      python: "3.6"
      condition: "$DJANGO_VERSION = 2.0.4"
  - provider: pypi
    skip_cleanup: true
    user: $PYPI_USER
    password: $PYPI_PASS
    distributions: "sdist bdist_wheel"
    on:
      tags: true
      python: "3.6"
      condition: "$DJANGO_VERSION = 2.0.4"
notifications:
  email: false
